#!/bin/bash

HOME_DIR=$(grep jelastic /etc/passwd | awk -F ":" '{print $6}')

function print_help() {
cat <<EOF
Purpose: Interact with S3 mounts

Usage: $0 [command]

Commands:

mount [bucket name]                	Mount a bucket
umount [bucket name]              	Unmount a bucket
list								List buckets
mountall 							Mount all buckets
umountall							Unmount all buckets



EOF
}

action=""
while [[ $# -gt 0 ]]; do
    param="$1"
    shift
    case $param in
        --help)
            print_help
            exit
        ;;
        mount)
            action="mount"
            if [ ! -z "$1" ]; then
            	if [ -f "$1" ]; then
            		mountLocation=$1
            	else
            		if [ -f $HOME_DIR/.s3fs/mounts/$1 ]; then
            			mountLocation=$HOME_DIR/.s3fs/mounts/$1
            		else
            			echo "Error: mount location not found"
            			exit 1;
            		fi;
            	fi;          
            else
            	echo "Error: mount location was not specified"
            	exit 1;
            fi;
            shift
        ;;
        umount)
			action="umount"
			if [ ! -z "$1" ]; then
            	if [ -f "$1" ]; then
            		mountLocation=$1
            	else
            		if [ -f $HOME_DIR/.s3fs/mounts/$1 ]; then
            			mountLocation=$HOME_DIR/.s3fs/mounts/$1
            		else
            			echo "Error: mount location not found"
            			exit 1;
            		fi;
            	fi;          
            else
            	echo "Error: mount location was not specified"
            	exit 1;
            fi;
            shift
		;;
		list)
			action="list"
        ;;
        mountall)
			action="mountall"
		;;
		umountall)
			action="umountall"
		;;
    esac;
done;


case $action in
	mount)
		mkdir -p $(awk '{print $3}' $mountLocation)
		/bin/bash $mountLocation
		if [ $? -eq 0 ]; then
			echo "$(awk {'print $2'} $mountLocation) mounted on $(awk {'print $3'} $mountLocation)";
		else
			echo "Cannot mount"
		fi;

	;;

	umount)
		fusermount -u $( awk '{print $3}' $mountLocation ) 
		if [ $? -eq 0 ]; then
			echo "$(awk {'print $2'} $mountLocation) unmounted from $(awk {'print $3'} $mountLocation)";
		else
			echo "Cannot unmount"
		fi;

	;;

	list)
		for bucketname in $(ls -1 ~/.s3fs/mounts/); do
        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
        		mount | grep -q $MOUNTPOINT 2>/dev/null
        		if [ $? -eq 0 ]; then
                	echo "$bucketname - MOUNTED on $MOUNTPOINT"
        		else
                	echo "$bucketname - NOT MOUNTED"
        		fi;
		done;
	;;

	mountall)
		for bucketname in $(ls -1 ~/.s3fs/mounts/); do
        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
        		mount | grep -q $MOUNTPOINT 2>/dev/null
        		if [ $? -ne 0 ]; then
                	/bin/bash ~/.s3fs/mounts/$bucketname
                	echo "$bucketname - MOUNTED on $MOUNTPOINT"
                else
                	echo "Operation failed"
                fi;
		done;
	;;

	umountall)
		for bucketname in $(ls -1 ~/.s3fs/mounts/); do
        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
        		mount | grep -q $MOUNTPOINT 2>/dev/null
        		if [ $? -eq 0 ]; then
                	fusermount -u $MOUNTPOINT
                	echo "$bucketname - UNMOUNTED from $MOUNTPOINT"
                else
                	echo "Operation failed"
                fi;
		done;
	;;

	*)
		print_help
		exit
	;;
esac
