#!/bin/bash

HOME_DIR=$(grep jelastic /etc/passwd | awk -F ":" '{print $6}')

function print_help() {
cat <<EOF
Purpose: Interact with S3 mounts

Usage: $0 [command]

Commands:

mount [bucket name]                	Mount a bucket
umount [bucket name]              	Unmount a bucket
list								List buckets
mountall 							Mount all buckets
umountall							Unmount all buckets



EOF
}

action=""
while [[ $# -gt 0 ]]; do
    param="$1"
    shift
    case $param in
        --help)
            print_help
            exit
        ;;
        mount)
            action="mount"
            if [ ! -z "$1" ]; then
            	if [ -f "$1" ]; then
            		mountLocation=$1
            	else
            		if [ -f $HOME_DIR/.s3fs/mounts/$1 ]; then
            			mountLocation=$HOME_DIR/.s3fs/mounts/$1
            		else
            			echo "Error: mount location not found"
            			exit 1;
            		fi;
            	fi;          
            else
            	echo "Error: mount location was not specified"
            	exit 1;
            fi;
            shift
        ;;
        umount)
			action="umount"
			if [ ! -z "$1" ]; then
            	if [ -f "$1" ]; then
            		mountLocation=$1
            	else
            		if [ -f $HOME_DIR/.s3fs/mounts/$1 ]; then
            			mountLocation=$HOME_DIR/.s3fs/mounts/$1
            		else
            			echo "Error: mount location not found"
            			exit 1;
            		fi;
            	fi;          
            else
            	echo "Error: mount location was not specified"
            	exit 1;
            fi;
            shift
		;;
		list)
			action="list"
        ;;
        mountall)
			action="mountall"
		;;
		umountall)
			action="umountall"
		;;
    esac;
done;


case $action in
	mount)
		/bin/bash $mountLocation

	;;

	umount)
		fusermount -u $( awk '{print $3}' $mountLocation )

	;;

	list)
		for bucketname in $(ls -1 ~/s3fs/mounts/); do
        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
        		mount | grep -q $MOUNTPOINT 2>/dev/null
        		if [ $? -eq 0 ]; then
                	echo "$bucketname - MOUNTED on $MOUNTPOINT"
        		else
                	echo "$bucketname - NOT MOUNTED"
        		fi;
		done;
	;;

	mountall)
		for bucketname in $(ls -1 ~/s3fs/mounts/); do
        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
        		mount | grep -q $MOUNTPOINT 2>/dev/null
        		if [ $? -eq 0 ]; then
                	/bin/bash ~/s3fs/mounts/$bucketname
                fi;
		done;
	;;

	umountall)
		for bucketname in $(ls -1 ~/s3fs/mounts/); do
        		MOUNTPOINT=$(awk '{print $3}' ~/.s3fs/mounts/$bucketname )
        		mount | grep -q $MOUNTPOINT 2>/dev/null
        		if [ $? -ne 0 ]; then
                	fusermount -u $MOUNTPOINT
                fi;
		done;
	;;

	*)
		print_help
		exit
	;;
esac
